export const extensions = [
  {
    id: 1,
    name: "YouTube Video Downloader",
    description:
      "A powerful tool allows you to easily download your favorite videos from YouTube with just a few clicks.",
    longDescription:
      "Introducing the YouTube Video Downloader Chrome Extension - a powerful tool allows you to easily download your favorite videos from YouTube with just a few clicks. With its user-friendly interface and lightning-fast download speeds, this extension is the perfect solution for anyone looking to save their favorite videos for offline viewing. Download now and experience the convenience of having your favorite YouTube videos at your fingertips!",
    price: 30,
    originalPrice: 45,
    category: "social",
    browsers: ["chrome"],
    rating: 5,
    totalRatings: 0,
    users: "1+",
    features: [
      "Download Popup",
      "URL Fetch",
      "Download Video From YouTube",
      "Able to change video quality",
      "Awesome User Interface",
      "Fetch YouTube Thumbnail too",
    ],
    tags: ["social", "youtube", "tools", "video downloader"],
    media: [
      {
        type: "video",
        url: `<iframe width="1182" height="665" src="https://www.youtube.com/embed/Y0vW-xrDH30" title="🔥 Build OWN YouTube Video Downloader Chrome Extension With #react  &amp; #CRXJS | [2023 - ST SABBIR]" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`, // Example YouTube embed URL
        thumbnail: "/placeholder-thumb.jpg",
      },
    ],
    screenshots: [
      "/placeholder-thumb.jpg",
      "/placeholder-thumb.jpg",
      "/placeholder-thumb.jpg",
    ],
    version: "1.2.7",
    size: "1.23 MB",
    lastUpdated: "Sep 26, 2024",
    permissions: ["No Permission Needed"],
    developer: {
      name: "Sabbir Hossian Shuvo",
      avatar: "https://avatars.githubusercontent.com/u/82939905?v=4",
      verified: true,
    },
    stats: {
      downloads: 2,
      likes: 5,
      views: 10,
    },
    isPopular: true,
    isFeatured: true,
    isNew: true,
    gradientFrom: "#8B5CF6",
    gradientTo: "#EC4899",
  },
  {
    id: 2,
    name: "SecureVault Pro",
    description:
      "Military-grade password manager with biometric authentication",
    longDescription:
      "Keep your digital life secure with advanced encryption, biometric locks, and seamless auto-fill across all your devices.",
    price: 29.99,
    category: "security",
    browsers: ["chrome", "firefox"],
    rating: 4.8,
    totalRatings: 892,
    users: "18K+",
    features: [
      "Biometric Auth",
      "256-bit Encryption",
      "Auto-fill",
      "Secure Notes",
      "2FA Support",
    ],
    tags: ["security", "password", "encryption", "privacy"],
    media: [
      {
        type: "video",
        url: `<iframe width="1182" height="665" src="https://www.youtube.com/embed/Y0vW-xrDH30" title="🔥 Build OWN YouTube Video Downloader Chrome Extension With #react  &amp; #CRXJS | [2023 - ST SABBIR]" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`, // Example YouTube embed URL
        thumbnail: "/placeholder.svg?height=400&width=600",
      },
    ],
    screenshots: ["/placeholder.svg?height=400&width=600"],
    version: "2.8.0",
    size: "1.8 MB",
    lastUpdated: "2024-12-08",
    permissions: ["Access to all websites", "Storage permissions"],
    developer: {
      name: "BrowserPlugins",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: true,
    },
    stats: {
      downloads: 18000,
      likes: 1650,
      views: 32000,
    },
    isPopular: true,
    isFeatured: false,
    isNew: false,
    gradientFrom: "#10B981",
    gradientTo: "#06B6D4",
    changelog: [
      {
        version: "3.2.1",
        date: "2024-12-10",
        changes: [
          "Fixed tab grouping bug",
          "Improved AI task suggestions",
          "Enhanced dark mode",
        ],
      },
      {
        version: "3.2.0",
        date: "2024-12-01",
        changes: [
          "Added AI-powered task prioritization",
          "New analytics dashboard",
          "Performance improvements",
        ],
      },
    ],
  },
  {
    id: 3,
    name: "DevTools Master",
    description: "Advanced developer tools with code snippets and API testing",
    longDescription:
      "Supercharge your development workflow with advanced debugging tools, code snippets manager, and integrated API testing suite.",
    price: 24.99,
    category: "developer",
    browsers: ["chrome"],
    rating: 4.7,
    totalRatings: 654,
    users: "12K+",
    features: [
      "Code Snippets",
      "API Testing",
      "Console Enhancement",
      "Network Monitor",
    ],
    tags: ["developer", "debugging", "api", "tools"],
    media: [
      {
        type: "image",
        url: "/placeholder.svg?height=400&width=600",
      },
    ],
    screenshots: ["/placeholder.svg?height=400&width=600"],
    version: "1.9.2",
    size: "3.2 MB",
    lastUpdated: "2024-12-12",
    permissions: ["Developer tools access", "Storage permissions"],
    developer: {
      name: "BrowserPlugins",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: true,
    },
    stats: {
      downloads: 12000,
      likes: 980,
      views: 28000,
    },
    isPopular: false,
    isFeatured: false,
    isNew: true,
    gradientFrom: "#3B82F6",
    gradientTo: "#1D4ED8",
  },
  {
    id: 4,
    name: "SocialBoost",
    description:
      "Social media management and analytics in one powerful extension",
    longDescription:
      "Manage all your social media accounts, schedule posts, and track analytics with this comprehensive social media toolkit.",
    price: 19.99,
    originalPrice: 34.99,
    category: "social",
    browsers: ["chrome", "firefox"],
    rating: 4.6,
    totalRatings: 423,
    users: "8K+",
    features: [
      "Multi-platform Support",
      "Post Scheduling",
      "Analytics Dashboard",
      "Hashtag Generator",
    ],
    tags: ["social", "marketing", "analytics", "scheduling"],
    media: [
      {
        type: "video",
        url: `<iframe width="1182" height="665" src="https://www.youtube.com/embed/Y0vW-xrDH30" title="🔥 Build OWN YouTube Video Downloader Chrome Extension With #react  &amp; #CRXJS | [2023 - ST SABBIR]" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`, // Example YouTube embed URL
        thumbnail: "/placeholder.svg?height=400&width=600",
      },
    ],
    screenshots: ["/placeholder.svg?height=400&width=600"],
    version: "1.5.3",
    size: "2.8 MB",
    lastUpdated: "2024-12-05",
    permissions: ["Access to social media sites", "Storage permissions"],
    developer: {
      name: "BrowserPlugins",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: true,
    },
    stats: {
      downloads: 8000,
      likes: 720,
      views: 15000,
    },
    isPopular: false,
    isFeatured: true,
    isNew: false,
    gradientFrom: "#F59E0B",
    gradientTo: "#EF4444",
  },
  {
    id: 5,
    name: "StreamlineUI",
    description: "Beautiful UI customization for popular websites and web apps",
    longDescription:
      "Transform your browsing experience with custom themes, layouts, and UI enhancements for your favorite websites.",
    price: 14.99,
    category: "utility",
    browsers: ["chrome", "firefox"],
    rating: 4.5,
    totalRatings: 789,
    users: "15K+",
    features: [
      "Custom Themes",
      "Layout Control",
      "Dark Mode",
      "Font Customization",
    ],
    tags: ["ui", "themes", "customization", "design"],
    media: [
      {
        type: "image",
        url: "/placeholder.svg?height=400&width=600",
      },
    ],
    screenshots: ["/placeholder.svg?height=400&width=600"],
    version: "2.3.1",
    size: "1.5 MB",
    lastUpdated: "2024-12-07",
    permissions: ["Access to all websites", "Storage permissions"],
    developer: {
      name: "BrowserPlugins",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: true,
    },
    stats: {
      downloads: 15000,
      likes: 1200,
      views: 22000,
    },
    isPopular: false,
    isFeatured: false,
    isNew: false,
    gradientFrom: "#8B5A2B",
    gradientTo: "#D97706",
  },
  {
    id: 6,
    name: "GameBooster Pro",
    description:
      "Optimize your browser for gaming with performance enhancements",
    longDescription:
      "Get the ultimate gaming experience in your browser with performance optimizations, FPS monitoring, and game-specific enhancements.",
    price: 22.99,
    category: "entertainment",
    browsers: ["chrome"],
    rating: 4.4,
    totalRatings: 312,
    users: "6K+",
    features: [
      "Performance Boost",
      "FPS Monitor",
      "Game Profiles",
      "Memory Optimization",
    ],
    tags: ["gaming", "performance", "optimization", "fps"],
    media: [
      {
        type: "video",
        url: `<iframe width="1182" height="665" src="https://www.youtube.com/embed/Y0vW-xrDH30" title="🔥 Build OWN YouTube Video Downloader Chrome Extension With #react  &amp; #CRXJS | [2023 - ST SABBIR]" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`, // Example YouTube embed URL
        thumbnail: "/placeholder.svg?height=400&width=600",
      },
    ],
    screenshots: ["/placeholder.svg?height=400&width=600"],
    version: "1.2.8",
    size: "2.4 MB",
    lastUpdated: "2024-12-11",
    permissions: ["Access to gaming websites", "System performance access"],
    developer: {
      name: "BrowserPlugins",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: true,
    },
    stats: {
      downloads: 6000,
      likes: 450,
      views: 12000,
    },
    isPopular: false,
    isFeatured: false,
    isNew: true,
    gradientFrom: "#DC2626",
    gradientTo: "#7C2D12",
  },
];
